### ISSUE TITLE
Integrate with backend "Feedback" page

### ISSUE THREAD

**Issue by dogakocak** [IMPORTRADER/NobetciBorsaApplication#40]
Please integrate screen. 

Endpoint is here

POST
/api/Feedback/AddFeedback

![image](https://github.com/IMPORTRADER/NobetciBorsaApplication/assets/94220642/d9de2d6c-ef44-4a38-9088-121278729e41)

**Comment by canbich** [comment]
tamamdır chief

**Comment by canbich** [comment]
closed
